title: Inner Light Studio
description: Art, Movement & Meditation Space
baseurl: "/inner-light-studio"
url: "https://davethackeray.github.io"

# Collections
collections:
  artworks:
    output: true
    permalink: /art/:title/
  meditations:
    output: true
    permalink: /spiritual/:title/
  workshops:
    output: true
    permalink: /movement/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - package.json
  - package-lock.json
  - src
  - .storybook
  - memory-bank
  - _sass
  - "*.scss"
