name: Deploy Jekyll site to Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      
      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle lock --add-platform ruby
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          bundle config set --local deployment true
          bundle install --jobs 4
          npm ci
      
      - name: Build Storybook
        run: |
          echo "Building Storybook..."
          npm run build-storybook
          echo "Storybook build complete"
          ls -la storybook-static/
      
      - name: Build Jekyll
        run: |
          echo "Building Jekyll site..."
          JEKYLL_ENV=production bundle exec jekyll build
          echo "Jekyll build complete"
          ls -la _site/
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Copy Storybook to Jekyll site
        run: |
          echo "Copying Storybook to Jekyll _site..."
          mkdir -p _site/storybook
          cp -r storybook-static/* _site/storybook/
          echo "Copy complete"
          ls -la _site/storybook/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4